
FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y \
    build-essential \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . /app
RUN pip install --upgrade pip

RUN pip install torch torchvision \
    --index-url https://download.pytorch.org/whl/cpu

RUN pip install \
    transformers \
    pillow \
    tqdm \
    wandb \
    datasets

RUN pip install -e .
CMD ["bash"]
