name: CI

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -e .

      - name: Run unit tests(excludes integration)
        run: |
          pytest tests -m "not integration"

      # - name: Run integration tests
      #   run: |
      #     pytest tests -m "integration"